Gianpi96
real-time-analytics
Repository navigation
Code
Issues
Pull requests
Actions
Projects
Wiki
Security and quality
Insights
Settings
.github/workflows/main.yml
Create main.yml #1
All jobs
Run details
Triggered via push now
@Gianpi96Gianpi96
pushed
 777383a
main
Status
Failure
Total duration
–
Artifacts
–
This workflow graph cannot be shown
A graph will be generated the next time this workflow is run.

Annotations
1 error
Error
No event triggers defined in `on`
Footer
© 2026 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Community
Docs
Contact
Manage cookies
Do not share my personal information
